[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = '*'
conflicted = '~${count}'
staged = '+${count}'
modified = '!${count}'
untracked = '?${count}'

[custom.update]
when = "[ -x /usr/bin/rpm-ostree ] && /usr/bin/rpm-ostree status --json | /usr/bin/jq -e \".deployments[0].booted == false\" > /dev/null;"
command = 'echo "New deployment staged"'
symbol = ""
format = " $symbol [($output)]($style) "
style = "italic green"