[shell]
disabled = false

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = '*'
conflicted = '~${count}'
staged = '+${count}'
modified = '!${count}'
untracked = '?${count}'

[aws]
format = '[$symbol($profile )(\($region\) )]($style)'
symbol = '☁️ '
style = 'bold yellow'
